### ISSUE TITLE
Funciones: Editar Usuario

### ISSUE THREAD

**Issue by JCastillo92** [JCastillo92/Mercado_Ambiental#2]
## Tareas Edit_tel_dir.jsp
- Realizar validaciones de los campos (el usuario no pueda ingresar datos que no son)
- Añadir el menú
- Para cambiar la contraseña debe haber 3 campos:
  ------ Contraseña actual
  ------ Nueva Contraseña
  ------ Repetir Contraseña
- Validar el cambio de contraseña
- Realizar los cambios de esos campos en la base (Update tb_usuarios)
- Mejorar la interfaz
- Aplicar el mismo estilo que las demás interfaces !

**Comment by jairdean** [comment]
Bryan pilas termina ese peque error que te da por confirmation de CI.
