### ISSUE TITLE
Trueque - Administrador

### ISSUE THREAD

**Issue by JCastillo92** [JCastillo92/Mercado_Ambiental#5]
- Nuevo JSP
- Tabla con todos los productos de estado 2
- Mail de confirmación al administrador que se puso a comprar
- Botones de acción en la tabla "Confirmar - Anular"
- En caso de confirmar
- [ ] El producto pasa a estado 3
- [ ] Se registra el trueque en la tabla histórico
- En caso de anular
- [ ] El producto vuelve a estado 1
- [ ] Eliminar el atributo "comprador" en la base

**Comment by jairdean** [comment]
la tarea Mail de confirmación al administrador que se puso a comprar, ya tengo el metodo, lo que falta es hacer que sirva el comprar trueque. jajajajaja
